[[build]]
name = "llm-knowledge-base-search-bot"
[build.config]
builder = "local"
image_name = "ooocheckitout/search_bot"
linked_repo = "llm-knowledge-base"
build_path = "src/search_bot"
image_registry.domain = "ghcr.io"
image_registry.account = "ooocheckitout"
