[[stack]]
name = "n8n"
deploy = true
[stack.config]
server = "master"
project_name = "llm-knowledge-base"
poll_for_updates = true
auto_update = true
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["n8n.yml"]
links = [
    "http://raspberrypi:5678/"
]
environment = """
NGROK_AUTHTOKEN='[[NGROK_AUTHTOKEN]]'
INITIAL_ADMIN_EMAIL='[[INITIAL_ADMIN_EMAIL]]'
INITIAL_ADMIN_PASSWORD='[[INITIAL_ADMIN_PASSWORD]]'
"""
