[[stack]]
name = "ollama"
deploy = true
[stack.config]
server = "worker-gpu"
project_name = "llm-knowledge-base"
poll_for_updates = true
auto_update = true
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["ollama.yml"]
