[[stack]]
name = "openwebui"
deploy = true
[stack.config]
server = "master"
project_name = "llm-knowledge-base"
poll_for_updates = true
auto_update = true
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["openwebui.yml"]
links = [
  "http://raspberrypi:3000/"
]
