[[stack]]
name = "postgres"
deploy = true
[stack.config]
server = "master"
project_name = "komodo"
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["postgres.yml"]
environment = """
POSTGRES_USER='[[POSTGRES_USER]]'
POSTGRES_PASSWORD='[[POSTGRES_PASSWORD]]'
"""