[[stack]]
name = "proxy"
deploy = true
[stack.config]
server = "master"
project_name = "llm-knowledge-base"
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["proxy.yml"]
links = [
    "http://raspberrypi/",
    "https://raspberrypi/",
    "http://raspberrypi:81/"
]

[[stack]]
name = "n8n"
deploy = true
[stack.config]
server = "master"
project_name = "llm-knowledge-base"
poll_for_updates = true
auto_update = true
linked_repo = "llm-knowledge-base"
webhook_enabled = false
run_directory = "docker"
file_paths = ["n8n.yml"]
links = [
    "http://raspberrypi:5678/"
]
environment = """
CLOUDFLARE_TUNNEL_TOKEN='[[CLOUDFLARE_TUNNEL_TOKEN]]'
INITIAL_ADMIN_EMAIL='[[INITIAL_ADMIN_EMAIL]]'
INITIAL_ADMIN_PASSWORD='[[INITIAL_ADMIN_PASSWORD]]'
"""
