[[stack]]
name = "proxy"
deploy = true
[stack.config]
server = "master"
project_name = "llm-knowledge-base"
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["proxy.yml"]
links = [
    "http://raspberrypi/",
    "https://raspberrypi/",
    "http://raspberrypi:81/"
]
