[[stack]]
name = "ollama"
deploy = true
[stack.config]
poll_for_updates = true
server = "worker-gpu"
project_name = "llm-knowledge-base"
linked_repo = "llm-knowledge-base"
run_directory = "docker"
file_paths = ["ollama.yml"]
links = [
  "http://ooocheckitout:11434/"
]
