name: n8n
services:
  ngrok-http:
    image: ngrok/ngrok:latest
    container_name: ngrok-http
    command:
      - "http"
      - "--url=quagga-ultimate-finch.ngrok-free.app"
      - "http://host.docker.internal:80"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      INITIAL_ADMIN_EMAIL: "${POSTGRES_USER}"
      INITIAL_ADMIN_PASSWORD: "${POSTGRES_PASSWORD}"

  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - N8N_PORT=5678
      - N8N_HOST=quagga-ultimate-finch.ngrok-free.app
      - WEBHOOK_URL=https://quagga-ultimate-finch.ngrok-free.app/
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Warsaw
      - TZ=Europe/Warsaw
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_samples:/home/samples
    restart: always
    image: "docker.n8n.io/n8nio/n8n"

  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    image: "docker.io/ollama/ollama:latest"

  openwebui:
    container_name: openwebui
    image: "ghcr.io/open-webui/open-webui:main"
    ports:
      - "8080:8080"
    volumes:
      - open_webui_data:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  postgres:
    image: "docker.io/postgres:latest"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "llm-knowledge-base"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    container_name: postgres

volumes:
  npm_data:
  npm_letsencrypt:
  n8n_data:
  n8n_samples:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Downloads/Databricks
  ollama_data:
  open_webui_data:
  postgres_data:
