name: n8n
services:
  ngrok-http:
    image: ngrok/ngrok:latest
    container_name: ngrok-http
    command:
      - "http"
      - "--url=quagga-ultimate-finch.ngrok-free.app"
      - "http://host.docker.internal:80"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}

  nginx-proxy-manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    environment:
      INITIAL_ADMIN_EMAIL: "${INITIAL_ADMIN_EMAIL}"
      INITIAL_ADMIN_PASSWORD: "${INITIAL_ADMIN_PASSWORD}"

  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    environment:
      - NODE_ENV=production
      - N8N_PORT=5678
      - N8N_HOST=quagga-ultimate-finch.ngrok-free.app
      - WEBHOOK_URL=https://quagga-ultimate-finch.ngrok-free.app/
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Warsaw
      - TZ=Europe/Warsaw
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_samples:/home/samples
    restart: always
    image: "docker.n8n.io/n8nio/n8n"

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/

  postgres:
    image: "docker.io/postgres:latest"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: unless-stopped
    container_name: postgres

volumes:
  npm_data:
  npm_letsencrypt:
  n8n_data:
  n8n_samples:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Downloads/Databricks
  pg_data:
  pgadmin_data:
