services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - shared
    container_name: ollama
    image: "docker.io/ollama/ollama:latest"
    restart: unless-stopped
    ports:
      - "11434:11434"

volumes:
  ollama-data:

networks:
  shared:
