services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    image: "docker.io/ollama/ollama:latest"

volumes:
  ollama:
