services:
  openwebui:
    container_name: openwebui
    image: "ghcr.io/open-webui/open-webui:main"
    ports:
      - "8080:8080"
    volumes:
      - open_webui_data:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ooocheckitout:11434

volumes:
  open_webui_data: