services:
  openwebui:
    container_name: openwebui
    image: "ghcr.io/open-webui/open-webui:main"
    #    ports:
    #      - "8080:8080"
    volumes:
      - openwebui-data:/app/backend/data
    networks:
      - shared
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ooocheckitout:11434

volumes:
  openwebui-data:

networks:
  shared:

