services:
  openwebui:
    image: "ghcr.io/open-webui/open-webui:main"
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://raspberrypi:11434

volumes:
  open-webui: