services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.27.9
    #    ports:
    #      - "9443:9443"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared
    restart: unless-stopped

volumes:
  portainer-data:

networks:
  shared:
