services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.27.9
    command: --http-enabled
    #    ports:
    #      - "9000:9000"
    #      - "9443:9443"
    environment:
      - TRUSTED_ORIGINS=portainer.bitspire.team
    volumes:
      - portainer-data:/data
      - /run/user/1000/docker.sock:/var/run/docker.sock
    networks:
      - shared
    restart: unless-stopped

volumes:
  portainer-data:

networks:
  shared:
