services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.27.9
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - shared
    restart: unless-stopped

volumes:
  portainer-data:

networks:
  shared:
