services:
  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/
    networks:
      - shared
#    ports:
#      - "80:80"
    container_name: pgadmin

  postgres:
    image: "docker.io/postgres:latest"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - shared
#    ports:
#      - "5432:5432"
    restart: unless-stopped
    container_name: postgres

volumes:
  pg_data:
  pgadmin_data:

networks:
  shared:

