services:
  postgres:
    image: "docker.io/postgres:latest"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "default"
    ports:
      - "15432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  pg-data:
